### ISSUE TITLE
Draw icon in bottom right

### ISSUE THREAD

**Issue by aslakhellesoy** [SMOC-AI/smoc-widget#3]
Acceptance criteria:

- [x] The Icon can change colour to any hex colour
- [x] The icon is displayed in the bottom right with 64px padding from the edges
- [x] No user interaction is needed to display the icon - it shows up immediately when the page loads

Tasks:

- [x] Design the icon
- [x] Decide on icon format (png, gif, svg, jpeg)
- [x] Modify `index.html` to install the widget as described in `README.md` - set `src='/index.js'` to load from local server
- [x] Modify `index.ts` to actually draw the icon - using the DOM API such as [document.createElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement)
- [x] Write som CSS to style the icon (set its position and size). Could be done with inline CSS.

**Comment by Bazo02** [comment]
#7 is done, closing the issue
